services:
  - type: web
    name: gorgon-clock
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn gorgon_clock.wsgi:application'
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.0
